- name: Create Openshift Origin cluster on Azure
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars.yaml

  tasks:
  - name: Main - Create a resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"

  - name: Main - Create storage account for registry
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: osstorageregistry{{ 100 | random }}
      type: Standard_LRS
    register: osstorageregistry

  - name: Main - Create storage account for persistent volumes
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: osstoragepv{{ 100 | random }}
      type: Standard_LRS
    register: osstoragepv

  - include: network.yaml
  - include: node.yaml
  - include: infra.yaml
  - include: master.yaml